### ISSUE TITLE
Able to Defib multiple times if Switching off and to weapon

### ISSUE THREAD

**Issue by CptHaxray** [ZacharyHinds/ttt2-role-mesmerist#6]
I've seen this happen multiple times on our server. I sadly do not know the exact timing. The Mesmerist player starts to Defib a player, and switches weapon at some point, reviving the player as a Thrall but keeping the Defib available for use a second time. 

Additionally, if a Mesmerist was killed while in the middle of defibbing someone, sometimes the dead person is revived regardless a few seconds later

**Comment by ZacharyHinds** [comment]
Thank you for catching this, I'd known about the revival bug and had intended to fix it for some time. Both should be fixed with the two most recent commits. Will push live to workshop shortly. Let me know if either bug continues to appear
